### ISSUE TITLE
Install fails with Yarn

### ISSUE THREAD

**Issue by neftaly** [coconut-xr/natuerlich#1]
When installing with yarn 3 I get this error:

```
@coconut-xr/natuerlich@npm:0.0.18 [7ac29] doesn't provide @react-three/fiber (pc7035), requested by @coconut-xr/koestlich
```

This most likely means that nauterlich needs `react-three-fiber` as a peer dependency.

**Comment by cc-bbohlender** [comment]
Thanks for the issue :)
The newest version should have this fixed :)

**Comment by neftaly** [comment]
Thanks! Unfortunatley it seems like there are some more dependency issues.

I followed the "getting started" example, but used Yarn instead of NPM. These deps were missing from the associated package.json's:

* xinteraction is missing:
  * react
  * @react-three/fiber
* koestlich is missing:
  * suspend-react
  * yoga-wasm-web

I can create new issues if you want to close this issue :)

**Comment by cc-bbohlender** [comment]
Thanks for the problem description!
I updated koestlich, natuerlich, and xinteraction and tested everything with yarn 3.6.1.
Please re-open if the problem persists in your environment. 💯

**Comment by neftaly** [comment]
Thanks Bela!
