### ISSUE TITLE
Augmented Reality environment is grey, bluring on meta quest 2

### ISSUE THREAD

**Issue by albirrkarim** [coconut-xr/natuerlich#2]
when I try the demo with meta quest 2. the environment is grey and blurring like this.

<img width="551" alt="image" src="https://github.com/coconut-xr/natuerlich/assets/29292018/a88bd987-dca4-4bb6-aa3b-5e4e3e86f8f8">

how can I achieve a color environment like this?
![a](https://raw.githubusercontent.com/coconut-xr/natuerlich/main/images/spatial-ui-example.gif)

is the meta quest 2 can't achieve an experience like that?

BTW What headset do you use to make that video?

**Comment by cc-bbohlender** [comment]
Yes, the meta quest 2's passthrough is limited to a blurry grey image.
We were using the Meta Quest Pro for the recording, however, also other cheaper headsets (e.g. Pico 4, Lynx R1, Quest 3) have color passthrough support.
