### ISSUE TITLE
MotionController is not available

### ISSUE THREAD

**Issue by Ledzz** [coconut-xr/natuerlich#3]
Hello! Great lib, trying to integrate to our project.
One major obstacle I've encountered is that MotionController is not available from the outside.
I suggest adding a Map<XRInputSource, MotionController> to a XRState.

If you think this is an ok solution, I can even prepare a PR.

**Comment by cc-bbohlender** [comment]
Hey @Ledzz 
In natuerlich such a map doesn't fit the design philosophy since we don't want to assume developers are using the Motion Controller. In contrast, developers can use the XRInputSources themselves to build any interaction device they want. Therefore, developers are free to build a state like a "Map<XRInputSource, MotionController>" themselves.

This design philosophy is based on our experience, but we are, of course, open to changes. Maybe you can explain why you need the MotionController and why you think this is necessary for most other developers. :)
Thanks ! :)

**Comment by Ledzz** [comment]
Thanks for the reply, @cc-bbohlender !
The main reason why we use MotionControllers (we are using three-stdlib version right now) is because we don't want to manually map gamepad api to buttons state in order to use controller's buttons (A, B, X, Y, thumbstick position etc).
Creating our own MotionController instance when we already have it inside the lib seems like unneccessary copy-pasting.

**Comment by cc-bbohlender** [comment]
The motion controller are currently only has the responsibility to update the visuals of the controller model and therefore not exposed in any datastructure.
I would argue that using the gamepad api is much more cleaner, less error prone, and more resistant against changes, and not much more work.

As a comprimise I can expose the motionController on the controllerModel. You can then build your own controller using "DynamicControllerModel" and receive the "MotionController" using
```
const ref = useRef(null)
useEffect(() => {
  ref.current.motionController //here you have it :)
}, [])
return <DynamicControllerModel ref={ref}/>
```
This solution would only be a workarround.

Alternatively I would love to see some helper functions that work using the gampad API, maybe we can collaborate on that so we can achieve yours goals and make general gamepad functionality available to all :)

**Comment by Ledzz** [comment]
> I would argue that using the gamepad api is much more cleaner, less error prone, and more resistant against changes, and not much more work.
I would agree if we didn't have to load controller profiles.

But I agree we can add some helper function.
Do you have any thoughts on how can it be implemented and if it is going to fit your library?

**Comment by cc-bbohlender** [comment]
@Ledzz I will expose a hook called `useInputSourceProfile(inputSource)` including type definitions.
Maybe you could think of the API that you would love to see for using the gamepad, e.g. `useXRGamepadButtonDown(inputSource, "x-button", () => console.log("down"))` or `<XRGamepad inputSource={inputSource} onDown={() => console.log("...")} onUp={() => console.log("")}`

(I think a stateful option that can be read in useFrame and a event based option should be created)

**Comment by Ledzz** [comment]
Yeah, I agree:

- `useXRGamepadButtonDown(inputSource, "x-button", () => console.log("down"), () => console.log("up"))` (added a release callback as well)
- `useXRGamepadValues(inputSource, values => console.log(values))`

I think this will be enough for now

**Comment by Ledzz** [comment]
@cc-bbohlender thank you! I think I'll be able to do it next week

**Comment by Ledzz** [comment]
@cc-bbohlender hello! Could you please check the MR? But please don't approve it yet, I'd like to update the docs if the api is ok to you.

**Comment by cc-bbohlender** [comment]
@Ledzz thank you for the PR, looks very promising, I will comment directly in the PR :)

**Comment by cc-bbohlender** [comment]
@Ledzz Thanks for all the effort and the awesome example!
We just posted about the new release :)
https://x.com/coconut_xr/status/1710252139111444501
