### ISSUE TITLE
grabbable onRelease triggers without ever beeing grabbed.

### ISSUE THREAD

**Issue by DerKorb** [coconut-xr/natuerlich#9]
From the code it looks like onRelease more or less is just triggered by an onLeave

**Comment by bbohlender** [comment]
please describe the issue, or is this a implementation question?
Grabbable uses pointer capture, for pointer capture onLeave is only executed when either the capture is canceled or the capture is released, therefore onLeave is a reasonable choice.

**Comment by DerKorb** [comment]
I would assume, onRelease should only trigger if I grabbed the item first. This is not the case, you can just hover the item, then unhover it. onLeave will trigger and then it will call onReleased. To fix this, the Grabbable component would have to track whether the item has been grabbed internally and only call onRelease if that variable is true.

**Comment by bbohlender** [comment]
should be fixed in the latest release
